package negocio;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Aplicado generated by hbm2java
 */
public class Aplicado  implements java.io.Serializable {


     private AplicadoId id;
     private Oferente oferente;
     private Puestos puestos;
     private Date fechaAplicacion;

    public Aplicado() {
    }

	
    public Aplicado(AplicadoId id, Oferente oferente, Puestos puestos) {
        this.id = id;
        this.oferente = oferente;
        this.puestos = puestos;
    }
    public Aplicado(AplicadoId id, Oferente oferente, Puestos puestos, Date fechaAplicacion) {
       this.id = id;
       this.oferente = oferente;
       this.puestos = puestos;
       this.fechaAplicacion = fechaAplicacion;
    }
   
    public AplicadoId getId() {
        return this.id;
    }
    
    public void setId(AplicadoId id) {
        this.id = id;
    }
    public Oferente getOferente() {
        return this.oferente;
    }
    
    public void setOferente(Oferente oferente) {
        this.oferente = oferente;
    }
    public Puestos getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Puestos puestos) {
        this.puestos = puestos;
    }
    public Date getFechaAplicacion() {
        return this.fechaAplicacion;
    }
    
    public void setFechaAplicacion(Date fechaAplicacion) {
        this.fechaAplicacion = fechaAplicacion;
    }




}


