package negocio;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1



/**
 * ServiciosPublicados generated by hbm2java
 */
public class ServiciosPublicados  implements java.io.Serializable {


     private ServiciosPublicadosId id;
     private Oferente oferente;
     private Servicios servicios;
     private Boolean estadoServicio;

    public ServiciosPublicados() {
    }

	
    public ServiciosPublicados(ServiciosPublicadosId id, Oferente oferente, Servicios servicios) {
        this.id = id;
        this.oferente = oferente;
        this.servicios = servicios;
    }
    public ServiciosPublicados(ServiciosPublicadosId id, Oferente oferente, Servicios servicios, Boolean estadoServicio) {
       this.id = id;
       this.oferente = oferente;
       this.servicios = servicios;
       this.estadoServicio = estadoServicio;
    }
   
    public ServiciosPublicadosId getId() {
        return this.id;
    }
    
    public void setId(ServiciosPublicadosId id) {
        this.id = id;
    }
    public Oferente getOferente() {
        return this.oferente;
    }
    
    public void setOferente(Oferente oferente) {
        this.oferente = oferente;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public Boolean getEstadoServicio() {
        return this.estadoServicio;
    }
    
    public void setEstadoServicio(Boolean estadoServicio) {
        this.estadoServicio = estadoServicio;
    }




}


