package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1

import java.sql.Date;





/**
 * CaracteristicasIncluidos generated by hbm2java
 */
public class CaracteristicasIncluidos  implements java.io.Serializable {


     private int idCaracteristicas;
     private int idPuestos;

    public CaracteristicasIncluidos() {
    }

    public CaracteristicasIncluidos(int idCaracteristicas, int idPuestos) {
        this.idCaracteristicas = idCaracteristicas;
        this.idPuestos = idPuestos;
    }

    public int getIdCaracteristicas() {
        return idCaracteristicas;
    }

    public void setIdCaracteristicas(int idCaracteristicas) {
        this.idCaracteristicas = idCaracteristicas;
    }

    public int getIdPuestos() {
        return idPuestos;
    }

    public void setIdPuestos(int idPuestos) {
        this.idPuestos = idPuestos;
    }
    
     

     
   
 



}


