package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idEmp;
     private String nombreEmp;
     private String telefono;
     private String latitud;
     private String longitud;
     private String descripcionEmp;
     private String correoEmp;
     private Date fechaRegistro;
     private String clave;
     private Set<PuestosPublicados> puestosPublicadoses = new HashSet<PuestosPublicados>(0);

    public Empresa() {
    }

    public Empresa(String clave, Integer idEmp, String nombreEmp, String ubicacionEmp, String latitud, String longitud, String descripcionEmp, String correoEmp, Date fechaRegistro) {
        this.clave = clave;
        this.idEmp = idEmp;
        this.nombreEmp = nombreEmp;
        this.telefono = ubicacionEmp;
        this.latitud = latitud;
        this.longitud = longitud;
        this.descripcionEmp = descripcionEmp;
        this.correoEmp = correoEmp;
        this.fechaRegistro = fechaRegistro;
    }

    public String getClave() {
        return clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }
    
    

    public String getLatitud() {
        return latitud;
    }

    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    public String getLongitud() {
        return longitud;
    }

    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

  
   
    public Integer getIdEmp() {
        return this.idEmp;
    }
    
    public void setIdEmp(Integer idEmp) {
        this.idEmp = idEmp;
    }
    public String getNombreEmp() {
        return this.nombreEmp;
    }
    
    public void setNombreEmp(String nombreEmp) {
        this.nombreEmp = nombreEmp;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String ubicacionEmp) {
        this.telefono = ubicacionEmp;
    }
    public String getDescripcionEmp() {
        return this.descripcionEmp;
    }
    
    public void setDescripcionEmp(String descripcionEmp) {
        this.descripcionEmp = descripcionEmp;
    }
    public String getCorreoEmp() {
        return this.correoEmp;
    }
    
    public void setCorreoEmp(String correoEmp) {
        this.correoEmp = correoEmp;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<PuestosPublicados> getPuestosPublicadoses() {
        return this.puestosPublicadoses;
    }
    
    public void setPuestosPublicadoses(Set<PuestosPublicados> puestosPublicadoses) {
        this.puestosPublicadoses = puestosPublicadoses;
    }




}


