package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1



/**
 * Habilidades generated by hbm2java
 */
public class Habilidades  implements java.io.Serializable {


     private HabilidadesId id;
     private String areaTrabajo;
     private String especializacion;

    public Habilidades() {
    }

	
    public Habilidades(HabilidadesId id) {
        this.id = id;
    }
    public Habilidades(HabilidadesId id, String areaTrabajo, String especializacion) {
       this.id = id;
       this.areaTrabajo = areaTrabajo;
       this.especializacion = especializacion;
    }
   
    public HabilidadesId getId() {
        return this.id;
    }
    
    public void setId(HabilidadesId id) {
        this.id = id;
    }
    public String getAreaTrabajo() {
        return this.areaTrabajo;
    }
    
    public void setAreaTrabajo(String areaTrabajo) {
        this.areaTrabajo = areaTrabajo;
    }
    public String getEspecializacion() {
        return this.especializacion;
    }
    
    public void setEspecializacion(String especializacion) {
        this.especializacion = especializacion;
    }




}


