package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puestos generated by hbm2java
 */
public class Puestos  implements java.io.Serializable {


     private Integer idPuesto;
     private String nombrePuesto;
     private Float salario;
     private String descripcionPuesto;
     private boolean estado;
     
     private String nombreEspecializacion;
     private String porcentajeespecializacion;
     
     private String latitud;
     private String longitud;
     
     private String nombreEmpresa;

    public Puestos() {
    }

    public Puestos(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }

    public Puestos(Integer idPuesto, String nombrePuesto, Float salario, String descripcionPuesto, boolean estado, String nombreEspecializacion, String porcentajeespecializacion, String latitud, String longitud, String nombreEmpresa) {
        this.idPuesto = idPuesto;
        this.nombrePuesto = nombrePuesto;
        this.salario = salario;
        this.descripcionPuesto = descripcionPuesto;
        this.estado = estado;
        this.nombreEspecializacion = nombreEspecializacion;
        this.porcentajeespecializacion = porcentajeespecializacion;
        this.latitud = latitud;
        this.longitud = longitud;
        this.nombreEmpresa = nombreEmpresa;
    }

    
    
    
    
    public Puestos( String lat, String lon,Integer idPuesto, String nombrePuesto, Float salario, String descripcionPuesto, boolean estado) {
        this.idPuesto = idPuesto;
        this.nombrePuesto = nombrePuesto;
        this.salario = salario;
        this.descripcionPuesto = descripcionPuesto;
        this.estado = estado;
        this.latitud = lat;
        this.longitud = lon;
    }

    public Puestos(Integer idPuesto, String nombrePuesto, Float salario, String descripcionPuesto, boolean estado, String nombreEspecializacion, String porcentajeespecializacion) {
        this.idPuesto = idPuesto;
        this.nombrePuesto = nombrePuesto;
        this.salario = salario;
        this.descripcionPuesto = descripcionPuesto;
        this.estado = estado;
        this.nombreEspecializacion = nombreEspecializacion;
        this.porcentajeespecializacion = porcentajeespecializacion;
    }
    
    
    
    
     public Puestos( String nombrePuesto, Float salario, String descripcionPuesto, boolean estado) {
        
        this.nombrePuesto = nombrePuesto;
        this.salario = salario;
        this.descripcionPuesto = descripcionPuesto;
        this.estado = estado;
    }

    public String getLatitud() {
        return latitud;
    }

    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    public String getLongitud() {
        return longitud;
    }

    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }
     
     
     

    public String getNombreEspecializacion() {
        return nombreEspecializacion;
    }

    public void setNombreEspecializacion(String nombreEspecializacion) {
        this.nombreEspecializacion = nombreEspecializacion;
    }

    public String getPorcentajeespecializacion() {
        return porcentajeespecializacion;
    }

    public void setPorcentajeespecializacion(String porcentajeespecializacion) {
        this.porcentajeespecializacion = porcentajeespecializacion;
    }
     
     
     

    public Integer getIdPuesto() {
        return idPuesto;
    }

    public void setIdPuesto(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }

    public String getNombrePuesto() {
        return nombrePuesto;
    }

    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }

    public Float getSalario() {
        return salario;
    }

    public void setSalario(Float salario) {
        this.salario = salario;
    }

    public String getDescripcionPuesto() {
        return descripcionPuesto;
    }

    public void setDescripcionPuesto(String descripcionPuesto) {
        this.descripcionPuesto = descripcionPuesto;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public String getNombreEmpresa() {
        return nombreEmpresa;
    }

    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    
     



}


