package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1



/**
 * PuestosPublicados generated by hbm2java
 */
public class PuestosPublicados  implements java.io.Serializable {


     private PuestosPublicadosId id;
     private Empresa empresa;
     private Puestos puestos;
     private Boolean estadoPuesto;

    public PuestosPublicados() {
    }

	
    public PuestosPublicados(PuestosPublicadosId id, Empresa empresa, Puestos puestos) {
        this.id = id;
        this.empresa = empresa;
        this.puestos = puestos;
    }
    public PuestosPublicados(PuestosPublicadosId id, Empresa empresa, Puestos puestos, Boolean estadoPuesto) {
       this.id = id;
       this.empresa = empresa;
       this.puestos = puestos;
       this.estadoPuesto = estadoPuesto;
    }
   
    public PuestosPublicadosId getId() {
        return this.id;
    }
    
    public void setId(PuestosPublicadosId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Puestos getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Puestos puestos) {
        this.puestos = puestos;
    }
    public Boolean getEstadoPuesto() {
        return this.estadoPuesto;
    }
    
    public void setEstadoPuesto(Boolean estadoPuesto) {
        this.estadoPuesto = estadoPuesto;
    }




}


